### ISSUE TITLE
运行demo提示错误

### ISSUE THREAD

**Issue by kxy000** [gstory0404/gromore#1]
感谢提供插件,运行示例的时候提示插件问题 ,麻烦指点下什么问题呢

An Observatory debugger and profiler on BKL AL20 is available at:
http://127.0.0.1:50850/qenUTkx0je4=/
E/flutter (10081): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method register on channel gromore)
E/flutter (10081): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (10081): <asynchronous suspension>
E/flutter (10081): #1      Gromore.register (package:gromore/gromore.dart:21:12)
E/flutter (10081): <asynchronous suspension>
E/flutter (10081): #2      IndexPageState._initSDK (package:gromore_example/main.dart:74:13)
E/flutter (10081): <asynchronous suspension>
E/flutter (10081):

**Comment by gstory0404** [comment]
暂不支持android
